### ISSUE TITLE
Some responses don't have links

### ISSUE THREAD

**Issue by wraasch** [ivanoblomov/vaccine-notifier#2]
I DMed 2 zip codes to @vaccinesignup and received the following clinics in response:
![image](https://user-images.githubusercontent.com/62122864/111233108-9aeb2100-85a9-11eb-86cf-294be621d688.png)

The St. Johns clinics do not have signup links an one of them is not within my chosen zip codes (90003). I wonder if there is something strange about the way St. Johns is entered into their database?

**Comment by ivanoblomov** [comment]
As suspected, this is a problem with LA County's data feed:
```json
    {
        "id": 73,
        "xParent": 3,
        "NumChildren": 3,
        "inactive": "",
        "organization": "Reported",
        "name": "St. Johns - Avalon Health Center",
        "addr1": "6818 Avalon Blvd.",
        "addr2": "Los Angeles, CA 90003",
        "vaccines": "p",
        "logo": "",
        "mapZoom": "https://www.google.com/maps/d/embed?mid=1AdIIUb669F7mV6J5A6McJo7eC5X67dfG&ll=33.9774517%2C-118.26497169999999&z=16",
        "notes": null,
        "notesSpn": "",
        "alt": "",
        "altSpn": "",
        "date": "",
        "time": "",
        "link": "",
        "secondDose": "",
        "full": "full",
        "comments": "",
        "commentsSpn": "",
        "times": [],
        "clinicFormat": 1,
        "system": ""
    },
```
I'll add code to add links conditionally.

**Comment by ivanoblomov** [comment]
Extracted #7 as a separate issue.
